trigger:
- master

variables:
  buildConfiguration: 'Release'


jobs:

- template: azure-pipelines.template.yml
  parameters:
    name: ubuntu_node_8
    vmImage: 'ubuntu-16.04'
    node_version: 8.x

- template: azure-pipelines.template.yml
  parameters:
    name: ubuntu_node_9
    vmImage: 'ubuntu-16.04'
    node_version: 9.x


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
  - script: dotnet test
    displayName: 'dotnet build $(buildConfiguration) test'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
